#!/bin/bash

NODE_INSTALL_VERSION=${NODE_INSTALL_VERSION:-v0.10.35}

curl https://raw.githubusercontent.com/creationix/nvm/v0.23.2/install.sh | bash
echo "source ~/.nvm/nvm.sh" >> ~/.bash_profile
source ~/.bash_profile
nvm install $NODE_INSTALL_VERSION
nvm use $NODE_INSTALL_VERSION
nvm alias default $NODE_INSTALL_VERSION

# Install node global module
npm i -g npm@next
npm i -g grunt-cli bower
